language: cpp
compiler: clang
sudo: required
dist: trusty

install:
  - sudo apt-get install -y qt5-default qttools5-dev-tools #install necessary Qt files

script:
  - qmake # -config release
  - make -j2

before_deploy:
# Set up git user name and tag this commit
  - git config --local user.name "garakmon"
  - git config --local user.email "garakmon@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: porymap
  skip_cleanup: true
  on:
    branches:
      - master
      - travis-ci
  #  tags: true
