
install:
  - set QTDIR=C:\Qt\5.11.1\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - qmake porymap.pro -config release
  - mingw32-make -j2
  - windeployqt release/porymap.exe

deploy:
  #release: myproduct-v$(appveyor_build_version)
  description: 'Built by AppVeyor'
  provider: GitHub
  auth_token:
    secure: MLSwoIXXuZaI9iKbxUSX7ErtiRW8Q9MSuPOqS8EYJj68f4sx8eERXWBLX7MpmmEb
  artifact: release/porymap.exe #/.*\.nupkg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: true
  on:
    #all_branches: true #
    branch: travis-ci                 # release from master branch only
    #appveyor_repo_tag: true        # deploy on tag push only
